services:
  eureka-sv:
    build:
      context: ./eureka-sv
      dockerfile: Dockerfile
    mem_limit: 512m
    ports:
      - "8761:8761"
    networks:
      - ciudadeshotel-network

  cities-service:
    build:
      context: ./cities-service
      dockerfile: Dockerfile
    mem_limit: 512m
    ports:
      - "8082:8082"
    networks:
      - ciudadeshotel-network

  hotels-service:
    build:
      context: ./hotels-service
      dockerfile: Dockerfile
    mem_limit: 512m
    ports:
      - "8083:8083"
    networks:
      - ciudadeshotel-network

networks:
  ciudadeshotel-network:


